package entity;
// Generated Jul 3, 2020 12:08:51 PM by Hibernate Tools 4.3.1



/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private Integer attendanceId;
     private Meeting meeting;
     private User user;
     private Byte status;

    public Attendance() {
    }

    public Attendance(Meeting meeting, User user, Byte status) {
       this.meeting = meeting;
       this.user = user;
       this.status = status;
    }
    
    public Attendance(int meetingId, int userId) {
       this.meeting=new Meeting(meetingId);
       this.user=new User(userId);
       this.status = 2;
    }
   
    public Integer getAttendanceId() {
        return this.attendanceId;
    }
    
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }
    public Meeting getMeeting() {
        return this.meeting;
    }
    
    public void setMeeting(Meeting meeting) {
        this.meeting = meeting;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


