package entity;
// Generated Jul 3, 2020 12:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer locationId;
     private String name;
     private String adress;
     private Integer size;
     private Set meetings = new HashSet(0);

    public Location() {
    }

    public Location(String name, String adress, Integer size, Set meetings) {
       this.name = name;
       this.adress = adress;
       this.size = size;
       this.meetings = meetings;
    }
   
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }
    public Set getMeetings() {
        return this.meetings;
    }
    
    public void setMeetings(Set meetings) {
        this.meetings = meetings;
    }




}


