package entity;
// Generated Jul 3, 2020 12:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Meeting generated by hbm2java
 */
public class Meeting  implements java.io.Serializable {


     private Integer meetingId;
     private Location location;
     private String name;
     private String shortDescription;
     private String longDescription;
     private String avatar;
     private Date time;
     private Set attendances = new HashSet(0);

    public Meeting() {
        
    }
    
    public Meeting(int meetingId){
        this.meetingId=meetingId;
    }
    
    public Meeting(Location location, String name, String shortDescription, String longDescription, String avatar, Date time) {
       this.location = location;
       this.name = name;
       this.shortDescription = shortDescription;
       this.longDescription = longDescription;
       this.avatar = avatar;
       this.time = time;
    }
    
    public Meeting(int meetingId, Location location, String name, String shortDescription, String longDescription, String avatar, Date time) {
       this.meetingId=meetingId;
       this.location = location;
       this.name = name;
       this.shortDescription = shortDescription;
       this.longDescription = longDescription;
       this.avatar = avatar;
       this.time = time;
    }

    public Meeting(Location location, String name, String shortDescription, String longDescription, String avatar, Date time, Set attendances) {
       this.location = location;
       this.name = name;
       this.shortDescription = shortDescription;
       this.longDescription = longDescription;
       this.avatar = avatar;
       this.time = time;
       this.attendances = attendances;
    }
   
    public Integer getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    public String getLongDescription() {
        return this.longDescription;
    }
    
    public void setLongDescription(String longDescription) {
        this.longDescription = longDescription;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


