package entity;
// Generated Jul 3, 2020 12:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String username;
     private String password;
     private Byte admin;
     private String email;
     private Byte active;
     private Set attendances = new HashSet(0);

    public User() {
        
    }
    
    public User(int userId)
    {
        this.userId=userId;
    }
    
    public User(Integer userId, String name, Byte admin, Byte active)
    {
        this.userId=userId;
        this.name=name;
        this.admin=admin;
        this.active=active;
    }
    
    public User(String name, String username, String password, Byte admin, String email, Byte active) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.admin = admin;
       this.email = email;
       this.active = active;
    }
    
    public User(String name, String username, String email) {
       this.name = name;
       this.username = username;
       this.email = email;
    }

    public User(String name, String username, String password, Byte admin, String email, Byte active, Set attendances) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.admin = admin;
       this.email = email;
       this.active = active;
       this.attendances = attendances;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Byte admin) {
        this.admin = admin;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


